# Generated by Django 4.2.16 on 2024-10-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='email_send',
            field=models.BooleanField(default=True, verbose_name='Рассылка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='male',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=100, verbose_name='Пол'),
        ),
    ]
