# Generated by Django 4.2.16 on 2024-10-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_email_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acount_type',
            field=models.CharField(choices=[('full', 'Полный пакет'), ('free', 'Бесплатный пакет')], default='free', max_length=100, verbose_name='Тип аккаунта'),
        ),
    ]
